XPOS336/XPOS336/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using XPOS336.AddOns;
using XPOS336.Models;
using XPOS336.ViewModel;

namespace XPOS336.Controllers
{
    public class CustomerController : Controller
    {
        private readonly CustomerModel customer;
        private readonly int pageSize;
        private VMResponse response = new VMResponse();

        public CustomerController(IConfiguration _config)
        {
            customer = new CustomerModel(_config);
            pageSize = int.Parse(_config["PageSize"]);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Index(string? filter, int? pageNumber, int? currPageSize)
        {
            List<VMTblMCustomer>? data = new List<VMTblMCustomer>();
            if (filter == null)
            {
                data = customer.GetAll();
            }
            else
            {
                data = customer.GetByFilter(filter);
            }
            ViewBag.Filter = filter;
            ViewBag.PageSize = currPageSize ?? pageSize;

            return View(Pagination<VMTblMCustomer>.Create(data, pageNumber ?? 1, ViewBag.PageSize));
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Detail(int id)
        {
            VMTblMCustomer? data = customer.GetById(id);

            ViewBag.Title = "Customer Detail";
            return View(data);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Add()
        {
            ViewBag.Title = "Add Customer";
            return View();
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse> Add(VMTblMCustomer data)
        {
            response = await customer.CreateAsync(data);

            return response;
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Edit(int id)
        {
            VMTblMCustomer? data = customer.GetById(id);
            ViewBag.Title = "Edit Customer";
            return View(data);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse> Edit(VMTblMCustomer data)
        {
            response = await customer.UpdateAsync(data);

            return response;
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Delete(int id)
        {
            ViewBag.Title = "Delete Customer Confirmation";
            return View(id);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse> Delete(int id, int userId)
        {
            response = await customer.DeleteAsync(id, userId);

            return response;
        }
    }
}

XPOS336/XPOS336/Views/Customer/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
<div class="card">
    <div class="card-body">
        <form id="frm-customer" asp-controller="customer" asp-action="add">
            <div class="card">
                <div class="card-header">
                    <p class="h1">Customer Add</p>
                </div>
                <div class="card-body">
                    <input type="hidden" name="CreateBy" value="1"/>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Nama <span class="text-danger"> *</span></span>
                        <input type="text" class="col-9 form-control" placeholder="Input Customer Name..." aria-label="Name" name="Name" aria-describedby="basic-addon1" required> 
                    </div>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Email <span class="text-danger"> *</span></span>
                        <input type="email" class="col-9 form-control" placeholder="Input Customer Email..." aria-label="Email" name="Email" aria-describedby="basic-addon1" required> 
                    </div>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Password <span class="text-danger"> *</span></span>
                        <input type="password" class="col-9 form-control" placeholder="Input Customer Password..." aria-label="Password" name="Password" aria-describedby="basic-addon1" id="password" required> 
                    </div>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Address <span class="text-danger"> *</span></span>
                        <input type="text" class="col-9 form-control" placeholder="Input Customer Address..." aria-label="Address" name="Address" aria-describedby="basic-addon1" required> 
                    </div>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Phone</span>
                        <input type="text" class="col-9 form-control" placeholder="Input Customer Phone..." aria-label="Phone" name="Phone" aria-describedby="basic-addon1">
                    </div>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Role Id <span class="text-danger"> *</span></span>
                        <input type="number" class="col-9 form-control" placeholder="Input Customer Role Id..." aria-label="RoleId" name="RoleId" aria-describedby="basic-addon1" required>
                    </div>
                    <div>
                        <ul id="errorContainer"></ul>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="input-group-text btn btn-primary" id="btnSubmit"><i class="fa-solid fa-floppy-disk"></i>  Submit</button>
                        <button class="btn btn-primary" type="button" id="btnLoading" disabled>
                            <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                            Loading...
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $("#staticModalLgLabel").html("@ViewBag.Title");

    $("#btnLoading").hide();

    $.validator.addMethod("strongPassword", 
        function (value, el) {
            return (/^(?=.*[!@@#$%^&*\/])(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(.{8,20})$/.test(value));
        },
        function (chkRes, el) {
            let pass = $(el).val();
            // console.log(pass);
            let txtAlert = "";
            if (!(/^(?=.*[!@@#$%^&*.\\/])/.test(pass))) {
                txtAlert += `<li class="text-black"><p class="m-0 text-danger">Customer Password must contained at least one special characters (!@@#$%^&*.\\/)</p> </li>`;
            }
            if (!(/^(?=.*[0-9])/.test(pass))) {
                txtAlert += `<li class="text-black"><p class="m-0 text-danger">Customer Password must contained at least one number characters [0-9] </p> </li>`;
            }
            if(!(/^(?=.*[a-z])/.test(pass))){
                txtAlert += `<li class="text-black" > <p class="m-0 text-danger" >Customer Password must contained at least one normal alphabet characters[a - z] </p> </li>`;
            }
            if (!(/^(?=.*[A-Z])/.test(pass))) {
                txtAlert += `<li class="text-black"><p class="m-0 text-danger">Customer Password must contained at least one capital alphabet characters [A-Z] </p> </li>`;
            }
            if (!(/^(.{8,20})$/.test(pass))) {
                txtAlert += `<li class="text-black" > <p class="m-0 text-danger" >Customer Password length must between 8 to 20 characters</p> </li>`;
            }
            
            if (txtAlert == "") {
                return false;
            }
            else{
                return txtAlert;
            }
        }
    );

    $("#frm-customer").validate({
        errorClass: "text-danger",
        errorLabelContainer:"#errorContainer",
        wrapper:"li",
        rules: {
            Name: {
                "minlength": 3,
                "maxlength": 50
            },
            Email: {
                "maxlength": 50
            },
            Password: {
                // "minlength": 8,
                "strongPassword" : true
            },
            Address: {
                "minlength": 3
            }
        },
        messages: {
            Name: {
                "required":"Customer Name is Required!",
                "minlength": "Customer Name must be at least 3 characters",
                "maxlength": "Customer Name must not exceed 50 characters"
            },
            Email: {
                "required": "Customer Email is Required!",
                "maxlength": "Customer Email must not exceed 50 characters"
            },
            Password: {
                "required": "Customer Password is Required!"
                // "minlength": "Customer Password must be at least 8 characters",
            },
            Address: {
                "required": "Customer Address is Required!",
                "minlength": "Customer Address must be at least 3 characters"
            },
            RoleId: {
                "required": "Customer Role is Required!"
            }
        }
    });

    $("#frm-customer").submit(function (event) {
        //Disable form submit
        event.preventDefault();
        if ($("#frm-customer").valid()) {
            $.ajax({
                url: '/Customer/Add',
                type: 'post',
                data: $("#frm-customer").serialize(),
                dataType: 'json',
                beforeSend: function () {
                    //Proses before send data
                    $("#btnSubmit").hide();
                    $("#btnLoading").show();
                },
                success: function (response) {
                    // debugger;
                    //Proses success send data
                    if (response.statusCode == 200 || response.statusCode == 201) {
                        location.reload();
                    }
                    else {
                        alert(response.message);
                    }
                },
                error: function (errResponse) {
                    debugger;
                }

            })
        }

    });
</script>

XPOS336/XPOS336/Views/Customer/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model int;
@{
    Layout = null;
}
<div class="card">
    <div class="card-body d-flex justify-content-center align-items-center">
        <i class="fa-solid fa-exclamation-triangle float-xxl-start text-danger m-2"></i>
        <span> Are you sure want to <span class="text-danger fw-bold">DELETE</span> Customer with ID = @Model ?</span>
    </div>
    <div class="card-footer">
        <button class="btn btn-danger" id="btnDelete">Confirm</button>
        <button class="btn btn-danger" type="button" id="btnLoading" disabled>
            <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
            Loading...
        </button>
        <button class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
    </div>
</div>


<script>
    $("#staticModalLgLabel").html("@ViewBag.Title");

    $("#btnLoading").hide();

    $("#btnDelete").click(() => {
        $.ajax({
            url: '/Customer/Delete',
            type: 'post',
            data: { "id": @Model, "userId": 3 },
            dataType: 'json',
            beforeSend: function () {
                //Proses before send data
                $("#btnDelete").hide();
                $("#btnLoading").show();
            },
            success: function (response) {
                // debugger;
                //Proses success send data
                if (response.statusCode == 200) {
                    location.reload();
                }
                else {
                    alert(response.message);
                }
            },
            error: function (errResponse) {
                debugger;
            }
        })
    })
</script>

XPOS336/XPOS336/Views/Customer/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model VMTblMCustomer?
@{
    Layout = null;
}

<div class="card">
    <div class="card-header h5">
        @(Model != null ? Model.Name : "Category Not Found")
    </div>
    <div class="card-body">
        @if (Model != null)
        {
            <div class="row">
                <div class="col-2"><b></b>Email</div>
                <div class="col-10">@Model.Email</div>
            </div>
            <hr />
            <div class="row">
                <div class="col-2"><b></b>Password</div>
                <div class="col-10">@Model.Password</div>
            </div>
            <hr />
            <div class="row">
                <div class="col-2"><b></b>Address</div>
                <div class="col-10">@Model.Address</div>
            </div>
            <hr />
            <div class="row">
                <div class="col-2"><b></b>Phone</div>
                <div class="col-10">@(Model.Phone ?? "-")</div>
            </div>
            <hr />
            <div class="row">
                <div class="col-2"><b></b>RoleId</div>
                <div class="col-10">@(Model.RoleId != null ? Model.RoleId : "-")</div>
            </div>
            <hr />
            <div class="row">
                <div class="col-2">CreateBy</div>
                <div class="col-4">@Model.CreateBy</div>
                <div class="col-2">UpdateBy</div>
                <div class="col-4">@(Model.UpdatedBy != null ? Model.UpdatedBy : "-")</div>
            </div>
            <hr />
            <div class="row">
                <div class="col-2">CreateDate</div>
                <div class="col-4">@Model.CreateDate?.ToString("dd-MM-yyyy")</div>
                <div class="col-2">UpdateDate</div>
                <div class="col-4">@(Model.UpdateDate?.ToString("dd-MM-yyyy") != null ? Model.UpdateDate?.ToString("dd-MM-yyyy") : "-")</div>
            </div>
        }
        else
        {
            <p>---Tidak ditemukan---</p>
        }
    </div>
</div>

<script>
    $("#staticModalLgLabel").html("@ViewBag.Title");
</script>

XPOS336/XPOS336/Views/Customer/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model VMTblMCustomer?;
@{
    Layout = null;
}
<div class="card">
    <div class="card-body">
        <form id="frm-customer" asp-controller="customer" asp-action="edit">
            <div class="card">
                <div class="card-header">
                    <p class="h1">Customer Edit</p>
                </div>
                <div class="card-body">
                    <input type="hidden" name="Id" value="@Model.Id" />
                    <input type="hidden" name="UpdatedBy" value="2" />
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Nama <span class="text-danger"> *</span></span>
                        <input type="text" class="col-9 form-control" placeholder="Input Customer Name..." aria-label="Name" name="Name" aria-describedby="basic-addon1" value="@Model.Name" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Email <span class="text-danger"> *</span></span>
                        <input type="email" class="col-9 form-control" placeholder="Input Customer Email..." aria-label="Email" name="Email" aria-describedby="basic-addon1" value="@Model.Email" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Password <span class="text-danger"> *</span></span>
                        <input type="password" class="col-9 form-control" placeholder="Input Customer Password..." aria-label="Password" name="Password" aria-describedby="basic-addon1" value="@Model.Password" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Address <span class="text-danger"> *</span></span>
                        <input type="text" class="col-9 form-control" placeholder="Input Customer Address..." aria-label="Address" name="Address" aria-describedby="basic-addon1" value="@Model.Address" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Phone</span>
                        <input type="text" class="col-9 form-control" placeholder="Input Customer Phone..." aria-label="Phone" name="Phone" aria-describedby="basic-addon1" value="@Model.Phone">
                    </div>
                    <div class="input-group mb-3">
                        <span class="col-3 input-group-text" id="basic-addon1">Role Id <span class="text-danger"> *</span></span>
                        <input type="number" class="col-9 form-control" placeholder="Input Customer Role Id..." aria-label="RoleId" name="RoleId" aria-describedby="basic-addon1" value="@Model.RoleId" required>
                    </div>
                    <div>
                        <ul id="errorCointainer"></ul>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="input-group-text btn btn-primary" id="btnEdit"><i class="fa-solid fa-floppy-disk"></i>  Edit</button>
                        <button class="btn btn-primary" type="button" id="btnLoading" disabled>
                            <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                            Loading...
                        </button>
                    </div>
                   
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $("#staticModalLgLabel").html("@ViewBag.Title");
    $("#btnLoading").hide();

    $("#frm-customer").validate({
        errorClass: "text-danger",
        errorLabelContainer: "#errorCointainer",
        wrapper: "li",
        rules: {
            Name: {
                "minlength": 3,
                "maxlength": 50
            },
            Email: {
                "maxlength": 50
            },
            Address: {
                "minlength": 3
            }
        },
        messages: {
            Name: {
                "required": "Customer Name is Required!",
                "minlength": "Variant Name must be at least 3 characters",
                "maxlength": "Variant Name must not exceed 50 characters"
            },
            Email: {
                "required": "Customer Email is Required!",
                "maxlength": "Variant Name must not exceed 50 characters"
            },
            Password: {
                "required": "Customer Password is Required!"
            },
            Address: {
                "required": "Customer Address is Required!",
                "minlength": "Variant Name must be at least 3 characters"
            },
            RoleId: {
                "required": "Customer Role is Required!"
            }
        }
    });

    $("#frm-customer").submit(function (event) {
        //Disable form submit
        event.preventDefault();
        if ($("#frm-customer").valid()) {
            $.ajax({
                url: '/Customer/Edit',
                type: 'post',
                data: $("#frm-customer").serialize(),
                dataType: 'json',
                beforeSend: function () {
                    //Proses before send data
                    $("#btnEdit").hide();
                    $("#btnLoading").show();
                },
                success: function (response) {
                    // debugger;
                    //Proses success send data
                    if (response.statusCode == 200 || response.statusCode == 201) {
                        location.reload();
                    }
                    else {
                        alert(response.message);
                    }
                },
                error: function (errResponse) {
                    debugger;
                }

            })
        }

    });
</script>

XPOS336/XPOS336/Views/Customer/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Pagination<VMTblMCustomer>

@{
    ViewData["Title"] = "Customer Page";
}


<div class="card">
    <div class="card-header">
        <p class="h1">Customer Page</p>
    </div>
    <div class="card-body">
        <div class="d-flex justify-content-between mb-4">
            <div>
                <button type="button" class="btn btn-success mb-3 " title="Add" data-bs-toggle="modal" data-bs-target="#staticModalLg"><strong>+</strong></button>
            </div>
            <div>
                <form id="frmFilter" asp-controller="Customer" asp-action="Index">
                    <div class="input-group mb-3">
                        <input id="filter" name="filter" type="text" class="form-control" placeholder="Search Customer Name" value="@ViewBag.Filter">
                        <button type="submit" class="input-group-text btn btn-secondary" id="iSearch"><i class="fa-solid fa-search"></i></button>
                    </div>
                </form>
            </div>
        </div>
        <div>
            <table class="table">
                <thead>
                    <tr>
                        <th class="text-center align-middle">Id</th>
                        <th class="text-center align-middle">Name</th>
                        <th class="text-center align-middle">Email</th>
                        <th class="text-center align-middle">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if(Model != null)
                    {
                        @foreach (VMTblMCustomer customer in Model)
                        {
                            <tr>
                                <td class="text-center align-middle">@customer.Id</td>
                                <td class="text-center align-middle">@customer.Name</td>
                                <td class="text-center align-middle">@customer.Email</td>
                                <td class="text-center align-middle">

                                    <button class="btn btn-secondary" title="Detail" data-bs-toggle="modal" data-bs-target="#staticModalLg" data-id="@customer.Id"><i class="fa-solid fa-list"></i>  </button>
                                    <button class="btn btn-primary" title="Edit" data-bs-toggle="modal" data-bs-target="#staticModalLg" data-id="@customer.Id"><i class="fa-solid fa-pen"></i></button>
                                    <button class="btn btn-danger" title="Delete" data-bs-toggle="modal" data-bs-target="#staticModalLg" data-id="@customer.Id"><i class="fa-solid fa-trash"></i></button>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">Data tidak ditemukan</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer d-flex justify-content-between">
        <div>
            <a asp-controller="customer" asp-action="index" asp-route-filter="@ViewBag.Filter" asp-route-currPageSize="@ViewBag.PageSize" asp-route-pageNumber="@(Model.PageIndex <= 1 ? Model.PageIndex:Model.PageIndex-1)" type="button" class="btn @(Model.PageIndex <=1 ? "disabled":"")" title="previous page"><i class="fas fa-backward bg-primary px-2 py-1 rounded text-white"></i></a>
            <div class="btn btn-light text-primary">@Model.PageIndex of @Model.TotalPages</div>
            <a asp-controller="customer" asp-action="index" asp-route-filter="@ViewBag.Filter" asp-route-currPageSize="@ViewBag.PageSize" asp-route-pageNumber="@(Model.PageIndex >= Model.TotalPages ? Model.PageIndex:Model.PageIndex+1)" type="button" class="btn @(Model.PageIndex >=Model.TotalPages ? "disabled":"")" title="next page"><i class="fas fa-forward bg-primary px-2 py-1 rounded text-white"></i></a>
        </div>

        <div class="d-flex align-items-center mx-2 my-1 gap-3 border border-primary rounded">
            <label class="mx-2 text-primary">Page Size</label>
            <select id="curr-page" class="bg-primary text-white border-primary rounded py-1">
                @for (int i = 5; i <= 20; i += 5)
                {
                    @if (ViewBag.PageSize == i)
                    {
                        <option value="@i" selected>@i</option>
                    }
                    else
                    {
                        <option value="@i">@i</option>
                    }
                }
            </select>
        </div>
    </div>
</div>

<script>
    $("#curr-page").change(function (e) {
        location.replace("/Customer/Index?filter=@ViewBag.Filter&orderBy=@ViewBag.OrderBy&currPageSize=" + $(this).val());
    })

    $(".btn-success").click(function (event) {
        // alert("Isi filter = " + $("#filter").val());
        $("#staticModalBodyLg").load("/Customer/Add");
        
    });

    $(".btn-secondary").click(function (e) {
        let catId = $(this).data("id");
        $("#staticModalBodyLg").load("/Customer/Detail/" + catId);
    })

    $(".btn-primary").click(function (event) {
        let catId = $(this).data("id");
        $("#staticModalBodyLg").load("/Customer/Edit/" + catId);
    });

    $(".btn-danger").click(function (e) {
        let catId = $(this).data("id");
        $("#staticModalBodyLg").load("/Customer/Delete/" + catId);
    })
</script>
