XPOS336/XPOS336/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using XPOS336.AddOns;
using XPOS336.Models;
using XPOS336.ViewModel;

namespace XPOS336.Controllers
{
    
    public class CategoryController : Controller
    {
       
        private readonly CategoryModel category;
        private VMResponse response = new VMResponse();

        private readonly int pageSize;


        public CategoryController(IConfiguration _config)
        {
            category = new CategoryModel(_config);
            pageSize = int.Parse(_config["PageSize"]);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Index(string? filter, int? pageNumber, int? currPageSize)
        {


            List<VMTblMCategory>? data = new List<VMTblMCategory>();
            if (filter == null)
            {
                data = category.GetAll();
            }
            else
            {
                data = category.GetByFilter(filter);
            }
            ViewBag.Filter = filter;
            ViewBag.PageSize = currPageSize ?? pageSize;

            return View(Pagination<VMTblMCategory>.Create(data, pageNumber ?? 1, ViewBag.PageSize));
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Detail(int id)
        {
            VMTblMCategory? data = category.GetById(id);

            ViewBag.Title = "Category Detail";
            return View(data);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Add()
        {
            ViewBag.Title = "Add Category";
            return View();
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task <VMResponse> Add(VMTblMCategory data)
        {
            response = await category.CreateAsync(data);
            
            return response;
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Edit(int id)
        {
            VMTblMCategory? data = category.GetById(id);
            ViewBag.Title = "Edit Category";
            return View(data);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse> Edit(VMTblMCategory data)
        {
            response = await category.UpdateAsync(data);

            return response;
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Delete(int id)
        {
            ViewBag.Title = "Delete Category Confirmation";
            return View(id);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse> Delete(int id, int userId)
        {
            response = await category.DeleteAsync(id,userId);

            return response;
        }
    }
}

XPOS336/XPOS336/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using XPOS336.Models;
using XPOS336.ViewModel;

namespace XPOS336.Controllers
{
    public class OrderController : Controller
    {
        private readonly OrderModel order;
        private readonly ProductModel product;
        private string? imageFolder;
        private VMResponse response = new VMResponse();

        public OrderController(IConfiguration _config,IWebHostEnvironment _webHostEnv)
        {
            order = new OrderModel(_config);
            product = new ProductModel(_config, _webHostEnv);
            imageFolder = _config["ImgFolder"];
        }
        public IActionResult Index()
        {
            List<VMTblMProduct>? data = new List<VMTblMProduct>();

            data = product.GetAll();

            ViewBag.ImageFolder = imageFolder;

            return View(data);
        }

        public IActionResult Details(List<VMTblTOrderDetail>? listCart, int totProduct, decimal estPrice)
        {
            ViewBag.Title = "Details Order";
            ViewBag.TotalProduct = totProduct;
            ViewBag.EstimatedPrice = estPrice;

            return View(listCart);
        }


        [HttpPost]
        public async Task <VMResponse?> Save(List<VMTblTOrderDetail>? listCart, int totProduct, decimal estPrice, int createBy, int custId)
        {
            VMTblTOrder data = new VMTblTOrder()
            {
                
                orderDetail = listCart,
                TotalQty = totProduct,
                Amount = estPrice,
                IsCheckout = false,
                CreateBy = createBy,
                CustomerId = custId

            };

            response = await order.CreateUpdateAsync(data);
            return response;
        }


        [HttpPost]
        public async Task <VMResponse?> CheckedOut(List<VMTblTOrderDetail>? listCart, int totProduct, decimal estPrice, int createBy, int custId)
        {
            VMTblTOrder data = new VMTblTOrder()
            {
                orderDetail = listCart,
                TotalQty = totProduct,
                Amount = estPrice,
                IsCheckout = true,
                CreateBy = createBy,
                CustomerId = custId

            };
            response = await order.CreateUpdateAsync(data);
            return response;
        }

        public IActionResult History(string? filter)
        {
            List<VMTblTOrder>? data = new List<VMTblTOrder>();
            if (filter == null)
            {
                data = order.GetAll();
            }
            else
            {
                data = order.GetByFilter(filter);
            }
            ViewBag.Filter = filter;

            return View(data);
        }

        public IActionResult OrderDetails(int orderHeaderId)
        {

            ViewBag.Title = "Detail History Order";
            return View();
        }

        [HttpPost]
        public async Task<VMResponse?> CheckedOutEdit(int orderHeaderId, int updateBy, bool isDeleted=false)
        {
            VMTblTOrder data = order.GetById(orderHeaderId);
            

            if(data != null)
            {
                data.UpdatedBy = updateBy;
                data.IsCheckout = (isDeleted ?false:true);
                data.IsDeleted = isDeleted;
                response = await order.CreateUpdateAsync(data);
            }
            else
            {
                response = new VMResponse();
                response.statusCode = System.Net.HttpStatusCode.NoContent;
                response.message = "Order does not exist";

            }
            

            return response;
        }
    }
}

XPOS336/XPOS336/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using XPOS336.AddOns;
using XPOS336.Models;
using XPOS336.ViewModel;

namespace XPOS336.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductModel product;
        private readonly VariantModel variant;
        private readonly CategoryModel category;
        private readonly int pageSize;
        private string? imageFolder;

        private VMResponse response = new VMResponse();


        public ProductController(IConfiguration _config, IWebHostEnvironment _webHostEnv)
        {
            product = new ProductModel(_config, _webHostEnv);
            variant = new VariantModel(_config);
            category = new CategoryModel(_config);
            imageFolder = _config["ImgFolder"];
            pageSize = int.Parse(_config["PageSize"]);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public List<VMTblMVariant>? GetVariantByCategoryId(int catId)
        {
            return variant?.GetAll().Where(v => v.CategoryId == catId).ToList();
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Index(string? filter, string? orderBy, int? pageNumber, int? currPageSize)
        {
            List<VMTblMProduct>? data = new List<VMTblMProduct>();
            if(filter == null)
            {
                data = product.GetAll();
            }
            else
            {
                data = product.GetByFilter(filter);
            }
            ViewBag.Filter = filter;
            ViewBag.ImageFolder = imageFolder;
            ViewBag.OrderBy = orderBy;
            ViewBag.PageSize = currPageSize ?? pageSize;


            return View(Pagination<VMTblMProduct>.Create(data, pageNumber ?? 1, ViewBag.PageSize));
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Detail(int id)
        {
            VMTblMProduct? data = product.GetById(id);

            ViewBag.Title = "Product Detail";
            ViewBag.ImageFolder = imageFolder;
            return View(data);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Add()
        {
            ViewBag.Title = "Add Product";
            ViewBag.Category = category.GetAll();
            ViewBag.Variant = variant.GetAll();


            return View();
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse?> AddAsync(VMTblMProduct formData)
        {
            try
            {

                response = await product.CreateAsync(formData);

            }
            catch
            {

            }
            return response;
        }


        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Edit(int id)
        {
            VMTblMProduct? data = product.GetById(id);
            ViewBag.Title = "Edit Product";
            ViewBag.Category = category.GetAll();
            ViewBag.ImageFolder = imageFolder;
            return View(data);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse> Edit(VMTblMProduct formData)
        {
            VMTblMProduct? data;

            try
            {
                response = await product.UpdateAsync(formData);
            }
            catch
            {

            }

            return response;
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Delete(int id)
        {
            ViewBag.Title = "Delete Product Confirmation";
            return View(id);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse> Delete(int id, int userId)
        {
            

            try
            {
                response = await product.DeleteAsync(id,userId);
            }
            catch
            {

            }

            return response;
        }
    }
}

XPOS336/XPOS336/Controllers/VariantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using XPOS336.AddOns;
using XPOS336.Models;
using XPOS336.ViewModel;

namespace XPOS336.Controllers
{
    public class VariantController : Controller
    {
        private readonly VariantModel variant;
        private readonly CategoryModel category;
        private readonly int pageSize;
        private VMResponse response = new VMResponse();

        public VariantController(IConfiguration _config)
        {
            variant = new VariantModel(_config);
            category = new CategoryModel(_config);
            pageSize = int.Parse(_config["PageSize"]);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Index(string? filter, int? pageNumber, int? currPageSize)
        {
            List<VMTblMVariant> data = new List<VMTblMVariant>();

            if (filter == null)
            {
                data = variant.GetAll();
            }
            else
            {
                data = variant.GetByFilter(filter);
            }
            ViewBag.Filter = filter;
            ViewBag.PageSize = currPageSize ?? pageSize;

            return View(Pagination<VMTblMVariant>.Create(data, pageNumber ?? 1, ViewBag.PageSize));
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Detail(int id)
        {
            VMTblMVariant? data = variant.GetById(id);

            ViewBag.Title = "Variant Detail";
            return View(data);
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Add()
        {
            ViewBag.Title = "Add Variant";
            ViewBag.Category = category.GetAll();
            return View();
        }

        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse> Add(VMTblMVariant data)
        {
            response = await variant.CreateAsync(data);

            return response;
        }


        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Edit(int id)
        {
            VMTblMVariant? data = variant.GetById(id);
            ViewBag.Title = "Edit Variant";
            ViewBag.Category = category.GetAll();
            return View(data);
        }


        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse> Edit(VMTblMVariant data)
        {
            response = await variant.UpdateAsync(data);

            return response;
        }


        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        public IActionResult Delete(int id)
        {
            ViewBag.Title = "Delete Variant Confirmation";
            return View(id);
        }


        [Authorize(Roles = "1", AuthenticationSchemes = "CookieAuth")]
        [HttpPost]
        public async Task<VMResponse> Delete(int id, int userId)
        {
            response = await variant.DeleteAsync(id, userId);

            return response;
        }
    }
}

XPOS336/XPOS336/Views/Shared/_Alert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    //GET ALERT MESSAGE FROM SESSION
    ViewBag.InfoMsg = Context.Session.GetString("infoMsg") ?? string.Empty;
    ViewBag.WarnMsg = Context.Session.GetString("warnMsg") ?? string.Empty;
    ViewBag.ErrMsg = Context.Session.GetString("errMsg") ?? string.Empty;

    //RESET ALERT MESSAGE FROM SESSION
    Context.Session.SetString("infoMsg", string.Empty);
    Context.Session.SetString("warnMsg", string.Empty);
    Context.Session.SetString("errMsg", string.Empty);
}

<!-- Alert -->
<div id="alertPlaceHolder">

</div>


<script>
    function alert(message, type) {
        $("#alertPlaceHolder").append(`
                        <div class="alert alert-${type} alert-dismissible" role="alert">
                        <i class="fa-solid fa-circle-info text-${type}"></i>
                        <span>${message}</span>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                `);
    }
    $(document).ready(() => {
       

        if ("@ViewBag.InfoMsg" != "") alert("@Html.Raw(ViewBag.InfoMsg)", "info");
        if ("@ViewBag.WarnMsg" != "") alert("@Html.Raw(ViewBag.WarnMsg)", "warning");
        if ("@ViewBag.ErrMsg" != "") alert("@Html.Raw(ViewBag.ErrMsg)", "danger");
    })
</script>

XPOS336/XPOS336/Views/Shared/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - XPOS336 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

XPOS336/XPOS336/Views/Shared/_Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">XPOS336</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1 align">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    @if(Context.Session.GetInt32("custRoleId") == 1)
                    {
                        <div class="dropdown ">
                            <button class="btn dropdown-toggle m-0 border-0 p-2" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                Action
                            </button>
                            <ul class="dropdown-menu p-2" aria-labelledby="dropdownMenuButton1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark dropdown-item " asp-area="" asp-controller="Category" asp-action="Index">
                                        <div class="d-flex align-items-center">
                                            <div class="the-icons d-flex justify-content-center "><i class="fa-solid fa-list "></i></div>
                                            <div>Category</div>
                                        </div>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Customer" asp-action="Index">
                                        <div class="d-flex align-items-center">
                                            <div class="the-icons d-flex justify-content-center "><i class="fa-solid fa-user "></i></div>
                                            <div>Customer</div>
                                        </div>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">
                                        <div class="d-flex align-items-center">
                                            <div class="the-icons d-flex justify-content-center "><i class="fa-solid fa-bag-shopping"></i></div>
                                            <div>Product</div>
                                        </div>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Variant" asp-action="Index">
                                        <div class="d-flex align-items-center">
                                            <div class="the-icons d-flex justify-content-center "><i class="fa-solid fa-layer-group "></i></div>
                                            <div>Variant</div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="dropdown ">
                            <button class="btn dropdown-toggle m-0 border-0 p-2" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                                Transaction
                            </button>
                            <ul class="dropdown-menu p-2" aria-labelledby="dropdownMenuButton2">
                                <li class="nav-item ">
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Order" asp-action="Index">
                                        <div class="d-flex align-items-center">
                                            <div class="the-icons d-flex justify-content-center "><i class="fa-solid fa-cart-shopping"></i></div>
                                            <div>Order</div>
                                        </div>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Order" asp-action="History">
                                        <div class="d-flex align-items-center">
                                            <div class="the-icons d-flex justify-content-center "><i class="fa-solid fa-file-invoice-dollar"></i></div>
                                            <div>Order History</div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    }
                </ul>
            </div>
            <div>
                @if (Context.Session.GetString("custName") != null)
                {
                    <div class="dropdown text-end">
                        <button class="btn dropdown-toggle m-0 border-0 p-2" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                            @Context.Session.GetString("custName") (@Context.Session.GetInt32("custRoleId"))
                        </button>
                        <ul class="dropdown-menu p-2 w-100" aria-labelledby="dropdownMenuButton2">
                            <li class="nav-item ">
                                <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="auth" asp-action="profile" asp-route-custId="@Context.Session.GetInt32("custId")">
                                    <div class="d-flex align-items-center">
                                        <div class="the-icons d-flex justify-content-center "><i class="fa-solid fa-user"></i></div>
                                        <div>Profile</div>
                                    </div>
                                </a>
                            </li>
                            <hr />
                            <li class="nav-item bg-danger  rounded">
                                <a class="nav-link text-white dropdown-item" asp-area="" asp-controller="auth" asp-action="logout">
                                    <div class="d-flex align-items-center">
                                        <div class="the-icons d-flex justify-content-center "><i class="fa-solid fa-right-from-bracket"></i></div>
                                        <div>Logout</div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="mx-2">
                        @Context.Session.GetString("custEmail");
                    </div>
                }
                else
                {
                    <a asp-controller="auth" asp-action="index" id='btn-login' class='btn btn-primary'>LOGIN</a>
                }
            </div>
            
        </div>
    </nav>
</header>

<script>
    // $("#btn-login").click(function(e){
    //     location.replace("/Auth/Index");
    // })
</script>

XPOS336/XPOS336/Views/Shared/_Layout-Baru.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XPOS336</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/XPOS336.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <p class="h1">INI LAYOUT BARU</p>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - XPOS336 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

XPOS336/XPOS336/Views/Shared/_Layout-New.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
    <h1>HALO</h1>
     @RenderBody()
     @* @IgnoreBody() *@
</div>

XPOS336/XPOS336/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XPOS336</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/XPOS336.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <!--  Header  -->
    <partial name="_Header" />
    <!--  Alert  -->
    <partial name="_Alert" />

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <!--  Footer  -->
    <partial name="_Footer"/>
    <!--  Modal  -->
    <partial name="_Modal"/>

    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

XPOS336/XPOS336/Views/Shared/_Modal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- Modal -->
<div class="modal fade" id="staticModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="staticModalBody">
                ...ini body modal
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="staticModalLg" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticModalLgLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticModalLgLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="staticModalBodyLg">
                ...
            </div>
        </div>
    </div>
</div>